# configuration file for production environment

# only log warning and error messages
log: "debug"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors 
show_errors: 0

# cache route resolution for maximum performance
route_cache: 1

plugins:
    Database:
        driver: 'mysql'
        host: 'sifau.cspvdo7mmaoe.ap-southeast-2.rds.amazonaws.com'
        database: 'hits'
        username: 'sifau'
        password: '03_SIS_was_not'
        dbi_params:
            RaiseError: 1
            AutoCommit: 1
        log_queries: 1
        connections:
            SIF:
                driver: 'mysql'
                host: 'sifau.cspvdo7mmaoe.ap-southeast-2.rds.amazonaws.com'
                database: 'X'
                username: 'sifau'
                password: '03_SIS_was_not'
                dbi_params:
                    RaiseError: 1
                    AutoCommit: 1
                log_queries: 1
            INFRA:
                driver: 'mysql'
                host: 'sifau.cspvdo7mmaoe.ap-southeast-2.rds.amazonaws.com'
                database: 'hits_sif3_infra'
                username: 'sifau'
                password: '03_SIS_was_not'
                dbi_params:
                    RaiseError: 1
                    AutoCommit: 1
                log_queries: 1


# HITS configuration
hits:
    # REQUEST = request->user, e.g. from Apache
    # user: 'REQUEST'				
    user: 'COOKIE:sif-hits-api'				

hits_create:
    command: "/home/scottp/nsip/sif-data/bin/timetable.sh"
    template: "dbi:mysql:database=TEMPLATE;host=sifau.cspvdo7mmaoe.ap-southeast-2.rds.amazonaws.com"
    username: 'sifau'
    password: '03_SIS_was_not'

